### ISSUE TITLE
Issues in the build script for musicdroid in Android Studio newest version

### ISSUE THREAD

**Issue by pubudu91** [Catrobat/Musicdroid#27]
Hi, 

I'm new to Catrobat and open source in general and I'm not exactly sure whether this is the kind of issue that should be brought up in here. Anyways the issue I had was when I tried to build the project using Android Studio (up-to-date version) it was giving a build error.

After a quick lookup, I found out that line 47 in the file Musicdroid/musicdroid/build.gradle had to be replaced by 'minifyEnabled false' after which the project built without any problems

**Comment by UtpalKumarJha** [comment]
The Project hasn't been upgraded to use the latest 1.0 version . I am still not sure when the organization members would do it . you can even comment that line out and still it would run just fine . However I still don't know why it hasn't been upgraded . Comments from other members of organization is appreciated .

**Comment by pubudu91** [comment]
Have they given up on this project? I see that there haven't been any major activity in a few months on this repo

**Comment by UtpalKumarJha** [comment]
This is an ongoing project and development work is still going on check other branches .
